config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # Signup
  resources :users, only: [ :new, :create ]

  # Sessions (login)
  resources :sessions, only: [ :new, :create, :destroy ]

  # Provide convenient routes
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy", as: :logout

  # Separate route for recaptcha
  post "/recaptcha_verify", to: "users#create", as: :recaptcha_verify

  # API routes
  resources :todo_lists do
  resources :tasks, only: [ :new, :create, :update, :destroy ] do
    member do
      patch :update_position
    end
  end
  resources :list_shares, only: [ :create, :destroy ]
end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
  has_many :list_shares, dependent: :destroy
  has_many :shared_users, through: :list_shares, source: :user

  validates :title, presence: true

  # For sharing functionality
  def shared_with?(user)
    shared_users.include?(user)
  end

  def permission_for(user)
    list_shares.find_by(user: user)&.permission_level
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [ :edit, :update, :destroy ]

  def index
    @todo_lists = current_user.accessible_todo_lists
    @todo_list = TodoList.new
  end

  def show
    @todo_list = TodoList.find(params[:id])
  end

  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)
    @todo_lists = current_user.accessible_todo_lists # Needed to re-render index if needed

    if @todo_list.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root_path }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            "new_todo_list",
            partial: "todo_lists/form",
            locals: { todo_list: @todo_list }
          )
        end
        format.html { redirect_to root_path, alert: "Title can't be blank" }
      end
    end
  end

  def edit
    render partial: "todo_lists/form", locals: { todo_list: @todo_list }
  end

  def update
    if @todo_list.update(todo_list_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to root_path, notice: "Updated." }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render partial: "todo_lists/form", locals: { todo_list: @todo_list }
        end
        format.html { render :edit }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path }
    end
  end

  private

  def set_todo_list
    @todo_list = current_user.accessible_todo_lists.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:title)
  end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= turbo_frame_tag dom_id(todo_list) do %>
  <%= form_with(model: todo_list) do |form| %>
    <% if todo_list.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo list from being saved:</h2>
        <ul>
          <% todo_list.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.submit "Create new To Do list", class: "btn primary" %>
    </div>
  <% end %>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">
  <%= turbo_frame_tag "todo_list_#{todo_list.id}" do %>
    <h3><%= todo_list.title %></h3>
    <% if todo_list.user == current_user %>
      <div id="share_form_<%= todo_list.id %>">
        <%= render "list_shares/form", todo_list: todo_list %>
      </div>
    <% end %>
    <div id="tasks_<%= todo_list.id %>" class="tasks_wrapper">
      <%= render todo_list.tasks %>
    </div>
    <%= render "tasks/form", task: Task.new(todo_list: todo_list) %>
    <div>
      <%= link_to "Edit", edit_todo_list_path(todo_list), data: { turbo_frame: "todo_list_#{todo_list.id}" }, class: "btn link" %>
      <%= button_to "Delete", todo_list_path(todo_list), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn danger" %>
    </div>
  <% end %>
</div>

app/views/todo_lists/create.turbo_stream.erb
<%= turbo_stream.append "todo_lists" do %>
  <%= render @todo_list %>
<% end %>

<%= turbo_stream.replace "new_todo_list" do %>
  <%= render "form", todo_list: TodoList.new %>
<% end %>

app/views/todo_lists/destroy.turbo_stream.erb
<%= turbo_stream.remove @todo_list %>

app/views/todo_lists/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@todo_list) do %>
  <%= render partial: "todo_lists/todo_list", locals: { todo_list: @todo_list } %>
<% end %>