config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # Signup
  resources :users, only: [ :new, :create ]

  # Sessions (login)
  resources :sessions, only: [ :new, :create, :destroy ]

  # Provide convenient routes
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy", as: :logout

  # Separate route for recaptcha
  post "/recaptcha_verify", to: "users#create", as: :recaptcha_verify

  # API routes
  resources :todo_lists do
  resources :tasks, only: [ :new, :create, :update, :destroy ] do
    member do
      patch :update_position
    end
  end
  resources :list_shares, only: [ :create, :destroy ]
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="home-index">
  <% if flash[:notice] %>
    <div class="flash-message notice">
      <p><%= flash[:notice] %></p>
    </div>
  <% end %>

  <% if current_user %>
    <div class="welcome-header">
      <p>Hello, <strong><%= current_user.email %></strong>! Nice to see you back.</p>
      <%= button_to "Logout", logout_path, method: :delete, class: "btn primary" %>
    </div>

    <div id="todo_lists">
      <%= render current_user.accessible_todo_lists %>
    </div>

    <div id="new_todo_list">
      <%= render "todo_lists/form", todo_list: TodoList.new %>
    </div>
  <% else %>
    <div class="text-center">
      <h1>Welcome!</h1>
      <p>New here? Signup or login to get started</p>
      <%= link_to "Signup", new_user_path %> |
      <%= link_to "Login", new_session_path %>
    </div>
  <% end %>
</div>